BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "wine_wine" (
	"id"	integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	"winename"	varchar(200) NOT NULL,
	"producer"	varchar(200) NOT NULL,
	"drinkfrom"	varchar(200) NOT NULL,
	"drinkto"	varchar(200) NOT NULL,
	"grapes"	varchar(200) NOT NULL,
	"nmbrbottles"	integer NOT NULL,
	"year"	varchar(200) NOT NULL,
	"country"	varchar(200) NOT NULL,
	"notes"	varchar(400) NOT NULL,
	"purchase"	varchar(200) NOT NULL,
	"region"	varchar(200) NOT NULL,
	"editdate"	date
);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (1,'Berlungo','Padre vino','2020','2024','34% Sangiovese 33% Merlot 33% Cabernet Sauvignon',6,'2017','Italien','Lorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsumLorem ipsum','','Lombardei',);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (2,'Hamilton Lara','Chan','2021','2020','ligula. Aliquam erat volutpat.',2,'2020','Iceland','luctus,','17.11.19','North Gyeongsang',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (3,'Amal Dunlap','Rosario','2019','2019','facilisis non, bibendum sed,',5,'2021','Peru','leo, in lobortis tellus','15.12.20','Gye',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (4,'Armand Le','Yang','2020','2020','Vestibulum ante ipsum primis',8,'2020','Saint Barthélemy','consequat purus. Maecenas libero est, congue','21.03.20','AN',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (5,'Joel Holcomb','Trujillo','2019','2020','vitae aliquam eros turpis',8,'2020','Andorra','Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor.','20.10.19','CT',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (6,'Keaton Knight','Fitzgerald','2020','2019','aliquet lobortis, nisi nibh',1,'2020','Mauritania','ac mi eleifend egestas. Sed pharetra, felis eget','01.11.20','O',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (7,'Devin Owen','Coleman','2020','2020','libero. Proin mi. Aliquam',7,'2020','Ecuador','lectus ante dictum mi, ac mattis','18.03.20','Henegouwen',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (8,'Valentine Stout','Freeman','2019','2021','pretium aliquet, metus urna',7,'2019','Brazil','Quisque ac','27.01.20','RM',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (10,'Hammett Kane','Albert','2021','2020','elit sed consequat auctor,',7,'2020','Azerbaijan','nonummy ut,','10.12.20','RM',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (11,'Cooper Erickson','Rodriguez','2019','2020','cursus et, magna. Praesent',12,'2019','Jordan','diam. Sed diam lorem,','06.03.19','WY',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (12,'Giacomo Monroe','Tran','2019','2020','sit amet orci. Ut',6,'2020','Uzbekistan','molestie','25.03.20','CA',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (13,'Kuame Lambert','Howe','2019','2020','vitae nibh. Donec est',4,'2020','Ghana','in, tempus eu, ligula. Aenean euismod mauris','02.05.19','Gujarat',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (14,'Nash Underwood','Daniel','2020','2020','pede. Nunc sed orci',8,'2019','Solomon Islands','dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare,','18.01.21','Wyoming',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (15,'Orson Garrison','Hodges','2019','2019','Curabitur dictum. Phasellus in',10,'2019','Trinidad and Tobago','ut odio vel est tempor bibendum. Donec','24.09.19','Ist',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (17,'Timothy Saunders','Johnston','2020','2020','rutrum non, hendrerit id,',4,'2019','Bonaire, Sint Eustatius and Saba','fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem','07.05.19','VB',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (18,'Gil Pruitt','Blankenship','2020','2019','accumsan interdum libero dui',2,'2020','Isle of Man','mauris ipsum porta elit, a feugiat tellus lorem eu','29.11.19','A',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (19,'Kato Hudson','Ball','2021','2020','dapibus quam quis diam.',7,'2020','Sint Maarten','et, eros. Proin ultrices. Duis volutpat nunc','03.07.20','Wisconsin',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (20,'Jared Fuller','Callahan','2019','2020','pharetra, felis eget varius',10,'2019','Tonga','netus et malesuada','25.05.19','Z.',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (21,'Theodore Holder','Whitley','2019','2020','elementum sem, vitae aliquam',8,'2020','Ireland','tortor nibh sit amet','13.01.20','Victoria',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (22,'Dieter Melendez','Pena','2021','2019','non, vestibulum nec, euismod',5,'2021','Central African Republic','odio a purus. Duis elementum,','16.03.20','PV',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (23,'Zephania Curtis','Ramos','2019','2019','fermentum arcu. Vestibulum ante',5,'2020','Guam','lorem fringilla','03.06.20','Zl',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (24,'Caesar Gallagher','Greene','2019','2020','Etiam vestibulum massa rutrum',5,'2020','Jamaica','Sed et libero. Proin mi.','17.06.19','SK',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (25,'Thor Stein','Gutierrez','2019','2020','vehicula. Pellentesque tincidunt tempus',1,'2019','Oman','Donec elementum, lorem','07.01.20','Zeeland',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (26,'Randall Goff','Burks','2019','2020','mattis. Cras eget nisi',6,'2020','Pitcairn Islands','Mauris magna. Duis dignissim','18.09.20','NSW',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (27,'Luke Mckinney','Ward','2020','2020','et tristique pellentesque, tellus',7,'2020','Mauritius','adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut','22.01.21','Yucatán',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (28,'Chandler Duran','English','2020','2019','sed dolor. Fusce mi',4,'2019','Monaco','a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris','14.04.20','PK',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (29,'Kibo Cook','Shaffer','2020','2020','habitant morbi tristique senectus',10,'2020','Jamaica','tincidunt dui augue eu','16.03.20','Louisiana',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (30,'Jarrod Jimenez','Puckett','2019','2020','Aenean massa. Integer vitae',12,'2019','Switzerland','eu,','03.10.19','Ivanovo Oblast',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (31,'Samson Welch','Phelps','2020','2019','dignissim. Maecenas ornare egestas',4,'2019','Sint Maarten','vitae nibh.','29.03.20','LU',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (32,'Graham Coleman','Joseph','2020','2019','lorem eu metus. In',11,'2019','Taiwan','tincidunt, nunc','28.07.20','Waals-Brabant',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (34,'Lester Holden','Mcintosh','2019','2020','sociis natoque penatibus et',9,'2019','Benin','a mi fringilla mi lacinia mattis.','30.03.19','G',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (35,'Harlan Ford','Harper','2020','2019','elit pede, malesuada vel,',11,'2021','Gambia','justo eu arcu. Morbi sit amet','18.01.20','Andalucía',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (36,'Kasimir Solomon','Wright','2020','2020','semper auctor. Mauris vel',8,'2019','Morocco','morbi tristique senectus et netus et malesuada','03.03.19','North Island',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (37,'Gray Houston','Dillard','2020','2020','montes, nascetur ridiculus mus.',5,'2020','Saint Vincent and The Grenadines','eu tellus. Phasellus elit pede, malesuada vel, venenatis vel,','03.12.20','OR',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (38,'Magee Sharp','Caldwell','2020','2020','venenatis vel, faucibus id,',8,'2019','Guam','magna. Lorem ipsum dolor sit amet,','26.09.19','Colorado',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (40,'Wayne Norris','Faulkner','2019','2019','ut eros non enim',8,'2019','Ghana','pede ac','12.03.19','JI',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (42,'Merrill Wheeler','Hubbard','2020','2020','vulputate, risus a ultricies',9,'2020','New Zealand','non arcu. Vivamus','10.11.19','Virginia',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (43,'Brock Mays','Moody','2020','2020','aliquet lobortis, nisi nibh',4,'2020','Sri Lanka','conubia nostra, per','18.06.19','Ontario',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (44,'Hunter Harvey','Barton','2020','2019','sem eget massa. Suspendisse',11,'2019','Guinea','pharetra sed, hendrerit a, arcu. Sed et','24.10.19','Delhi',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (45,'Samson Tyson','Olson','2020','2020','Vivamus sit amet risus.',2,'2020','Turks and Caicos Islands','fermentum fermentum arcu. Vestibulum ante','22.09.20','Tamil Nadu',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (46,'Wyatt Henson','George','2020','2020','Sed nunc est, mollis',6,'2020','Palau','Cras dictum ultricies ligula. Nullam enim. Sed','04.07.20','West-Vlaanderen',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (47,'Cyrus Mcguire','Strickland','2020','2019','neque sed dictum eleifend,',11,'2019','Kenya','interdum enim non nisi. Aenean eget metus. In nec','07.09.19','ANT',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (48,'Castor Dejesus','King','2020','2019','ac mi eleifend egestas.',11,'2019','Venezuela','Sed neque. Sed eget lacus. Mauris non dui','17.10.19','C',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (49,'Tad Holloway','Mullen','2019','2019','Pellentesque tincidunt tempus risus.',1,'2020','Cuba','Nam porttitor scelerisque','24.02.19','Veracruz',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (50,'Nolan Vaughn','Horton','2020','2019','tempus scelerisque, lorem ipsum',1,'2021','Comoros','arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus.','19.03.20','Minas Gerais',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (51,'Dominic Hendrix','Tanner','2020','2019','in, dolor. Fusce feugiat.',4,'2019','Azerbaijan','Sed eu eros. Nam consequat','06.07.19','SI',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (52,'Abraham Page','Jennings','2020','2019','Integer eu lacus. Quisque',5,'2019','Burkina Faso','ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin','31.10.20','Castilla y León',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (55,'Duncan Burks','Sawyer','2020','2019','et magnis dis parturient',8,'2021','Costa Rica','consectetuer','03.02.20','RI',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (56,'Ian Vaughan','Cook','2020','2019','varius orci, in consequat',8,'2020','Chad','at auctor ullamcorper, nisl arcu iaculis enim, sit','07.05.20','RJ',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (58,'Merritt Cote','Clayton','2020','2019','lorem ac risus. Morbi',3,'2019','Taiwan','Curabitur massa. Vestibulum','26.06.19','JB',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (59,'Graiden Howard','Leon','2020','2020','orci. Ut sagittis lobortis',10,'2020','Saudi Arabia','purus','24.11.20','IL',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (60,'Quinlan Joyner','Wagner','2020','2019','pulvinar arcu et pede.',4,'2020','Sierra Leone','Donec at arcu.','19.12.20','Wyoming',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (61,'Ezekiel Osborn','Davis','2019','2020','libero. Morbi accumsan laoreet',11,'2020','Vanuatu','eros. Proin ultrices.','09.11.19','LAZ',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (62,'Cody Alvarado','Harrison','2020','2020','eros nec tellus. Nunc',2,'2020','Mauritius','velit eu sem.','09.04.20','YAR',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (63,'Baker Cooke','Horne','2020','2020','mattis ornare, lectus ante',4,'2019','Syria','metus urna convallis','06.01.20','North Island',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (64,'Ahmed Giles','Schneider','2021','2020','orci. Ut semper pretium',5,'2020','Finland','at, egestas a, scelerisque sed, sapien. Nunc','07.07.20','Swiętokrzyskie',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (65,'Walker Strong','Ellison','2019','2021','Quisque ornare tortor at',11,'2019','Indonesia','a, dui. Cras pellentesque. Sed dictum.','15.09.19','Bahia',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (66,'Herrod Mcgee','Mckee','2019','2019','Sed nec metus facilisis',1,'2020','Sudan','Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,','10.05.20','KD',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (67,'Odysseus Lowe','Stout','2020','2020','hendrerit. Donec porttitor tellus',2,'2020','Congo (Brazzaville)','magna nec quam. Curabitur','23.09.19','HH',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (68,'Dante Baker','Cantrell','2020','2021','purus mauris a nunc.',2,'2020','Jersey','orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec','17.02.20','Luik',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (69,'Denton Case','Keith','2020','2019','ipsum. Phasellus vitae mauris',7,'2020','China','molestie tortor nibh sit amet orci. Ut','19.01.20','Bryansk Oblast',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (70,'Norman Paul','Wolfe','2019','2020','auctor ullamcorper, nisl arcu',5,'2020','Guinea-Bissau','lobortis, nisi','05.12.20','IX',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (71,'Reese Mccarthy','Newton','2021','2019','luctus sit amet, faucibus',11,'2019','South Sudan','et, euismod et, commodo at, libero.','01.12.20','São Paulo',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (72,'Lee Weaver','Wheeler','2019','2019','molestie. Sed id risus',10,'2020','French Southern Territories','Curabitur sed','06.03.19','BRY',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (73,'Lamar Medina','Dorsey','2020','2020','ornare. In faucibus. Morbi',7,'2020','Iran','magna. Duis dignissim tempor','31.01.21','AST',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (75,'Eaton Steele','Cardenas','2020','2020','Vestibulum ut eros non',9,'2020','Haiti','Proin ultrices. Duis volutpat nunc','23.02.19','Bengkulu',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (76,'Moses Buchanan','Weeks','2020','2020','Nullam nisl. Maecenas malesuada',9,'2019','Lesotho','dignissim. Maecenas ornare','26.10.19','PUG',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (77,'Ferdinand Page','Hardy','2019','2020','quis arcu vel quam',9,'2021','Guam','accumsan laoreet ipsum. Curabitur consequat,','23.12.20','Yuc',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (79,'Fletcher Kramer','Winters','2019','2019','eu tellus eu augue',9,'2020','India','ornare, lectus ante','23.03.19','Abruzzo',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (80,'Bernard Nielsen','Atkinson','2020','2020','euismod enim. Etiam gravida',7,'2019','Central African Republic','sed tortor. Integer aliquam','10.03.20','PU',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (81,'Jameson Mosley','Gregory','2021','2020','Mauris quis turpis vitae',2,'2020','Åland Islands','quis accumsan convallis, ante lectus convallis est, vitae sodales','02.11.20','QC',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (82,'Merritt Best','Spence','2019','2019','risus. Donec egestas. Duis',11,'2020','Benin','sit amet massa. Quisque porttitor eros nec tellus.','25.09.20','KY',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (83,'Jonah Meyers','Williams','2019','2020','dui. Cras pellentesque. Sed',12,'2020','Russian Federation','risus, at fringilla purus mauris a nunc. In at','20.05.19','NI',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (84,'Reese Norton','Boyer','2020','2019','neque sed dictum eleifend,',2,'2019','Bulgaria','pellentesque. Sed dictum. Proin eget','17.10.19','AC',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (85,'Barclay Baker','Bradshaw','2019','2019','fermentum risus, at fringilla',11,'2021','Bahrain','consectetuer rhoncus. Nullam velit dui, semper et,','16.01.21','Connacht',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (86,'Ulysses Walters','Marsh','2020','2019','lorem ipsum sodales purus,',11,'2020','South Georgia and The South Sandwich Islands','ridiculus mus. Proin','21.07.20','NT',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (87,'Stephen Sharp','French','2020','2020','et ipsum cursus vestibulum.',7,'2020','Brazil','nunc interdum feugiat. Sed nec metus facilisis lorem','24.02.19','PR',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (88,'Felix Nieves','Johnston','2020','2019','egestas. Sed pharetra, felis',4,'2020','Jersey','sed','09.04.19','Provence-Alpes-Côte d''Azur',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (89,'Drake Copeland','Chavez','2019','2021','Nullam nisl. Maecenas malesuada',11,'2020','Zimbabwe','eget metus','15.01.21','ON',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (90,'Curran Snyder','Serrano','2019','2020','Pellentesque tincidunt tempus risus.',6,'2020','Myanmar','quis accumsan convallis, ante lectus convallis est, vitae','29.06.20','Gelderland',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (91,'Kane Potter','Ferrell','2019','2019','magna. Nam ligula elit,',10,'2019','Czech Republic','auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare','21.10.20','Guanacaste',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (92,'Arsenio Thompson','Mccarty','2021','2019','adipiscing ligula. Aenean gravida',4,'2019','Burkina Faso','non leo. Vivamus','30.01.20','KL',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (93,'Rafael Chan','Oneil','2020','2019','velit. Quisque varius. Nam',4,'2020','Croatia','nulla. Cras eu','22.07.20','Vienna',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (94,'Brennan Whitney','Fitzgerald','2020','2019','natoque penatibus et magnis',12,'2021','Sudan','suscipit, est ac facilisis facilisis,','04.04.20','LX',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (95,'Keegan Pennington','Oconnor','2019','2020','nisl sem, consequat nec,',1,'2020','Chile','mi. Aliquam','26.07.20','Wie',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (96,'Clarke Crawford','Drake','2020','2020','eleifend non, dapibus rutrum,',2,'2020','Suriname','et risus. Quisque libero lacus,','10.05.20','Antwerpen',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (97,'Aaron Parrish','Contreras','2020','2020','mauris, rhoncus id, mollis',3,'2019','Greenland','Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat','25.09.19','Quebec',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (98,'Joseph Bonner','Sexton','2021','2020','aliquet, metus urna convallis',2,'2019','Congo (Brazzaville)','leo. Cras vehicula aliquet libero.','14.11.20','BU',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (99,'Walter Valentine','Hobbs','2020','2020','feugiat metus sit amet',1,'2020','Switzerland','laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi','27.12.20','MA',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (100,'Elton Watson','Mckenzie','2020','2019','risus. Morbi metus. Vivamus',9,'2019','Western Sahara','Mauris quis turpis vitae','18.07.20','Paraná',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (101,'Armando Mooney','Acevedo','2020','2019','nibh. Aliquam ornare, libero',2,'2020','Jamaica','nec tempus mauris erat eget','20.11.19','LA',NULL);
INSERT INTO "wine_wine" ("id","winename","producer","drinkfrom","drinkto","grapes","nmbrbottles","year","country","notes","purchase","region","editdate") VALUES (102,'','','','','',0,'','','','','',NULL);
COMMIT;
