insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Redbird Flower', 'Space Brands Limited', 2004, 2011, 2005, 13);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Narrowleaf Yucca', 'Roxane Laboratories, Inc', 1992, 1961, 1998, 1);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Royal Snoutbean', 'Ranbaxy Pharmaceuticals Inc.', 1972, 1998, 1998, 3);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Yellow Screwstem', 'Ajes Pharmaceuticals,LLC', 2001, 1993, 2009, 40);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Chromatochlamys Lichen', 'Breckenridge Pharmaceutical, Inc.', 2006, 2012, 1991, 24);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Sabaigrass', 'American Health Packaging', 2008, 2008, 1998, 33);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Xanthoparmelia Lichen', 'Kinray Inc.', 2010, 2005, 1985, 28);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Cucamonga Manroot', 'Alaven Pharmaceutical LLC', 2010, 2009, 2009, 21);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Sickle Dichelyma Moss', 'Wockhardt USA LLC.', 2005, 1999, 2005, 38);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Heartleaf Twayblade', 'Motto-Elektro Ltd.', 1998, 1988, 1999, 34);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Burnet Oak', 'Uriel Pharmacy Inc.', 2000, 2012, 2006, 21);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Needle Blue-eyed Grass', 'CHAIN DRUG MARKETING ASSOCIATION INC', 1996, 2000, 2009, 21);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Tropical Sensitive Pea', 'American Health Packaging', 1995, 2008, 2005, 12);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Bush''s Purple Coneflower', 'Topco Associates LLC', 1992, 2006, 2005, 34);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Waldo Buckwheat', 'Teva Pharmaceuticals USA Inc', 2004, 2010, 2004, 31);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Fishtail Swordfern', 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 2003, 1998, 2002, 26);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Yellow And White Monkeyflower', 'Biogen Idec Inc.', 1996, 2011, 1985, 27);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Xiao Ye Li', 'KMART CORPORATION', 2005, 2006, 2008, 30);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Barranca Brush', 'H and P Industries, Inc. dba Triad Group', 1989, 2000, 2000, 27);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Synedrella', 'Rebel Distributors Corp', 2003, 2005, 2004, 32);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Tuliptree', 'Amneal Pharmaceuticals', 1988, 2012, 2008, 33);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Roundhead Lespedeza', 'Avon Products, Inc', 1988, 1992, 1970, 18);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Wright''s Plantain', 'Expanscience Laboratories d/b/a Mustela', 1994, 2009, 2005, 28);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Cedros Milkvetch', 'Enovachem Manufacturing', 2005, 1993, 2012, 15);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('European Plum', 'Dolgencorp LLC', 2011, 2012, 2006, 9);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Water Chestnut', 'Taro Pharmaceuticals U.S.A., Inc.', 1991, 1997, 1988, 11);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Mexican Arrowwood', 'AvPAK', 1995, 2004, 1998, 27);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Hassea Lichen', 'Forces of Nature', 2011, 1974, 2007, 6);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Entosthodon Moss', 'HANLIM PHARM. CO., LTD.', 2003, 1994, 2004, 8);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Wagner''s Cyrtandra', 'ALK-Abello, Inc.', 2009, 2006, 2005, 10);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Smallhead Cat''s Ear', 'Mallinckrodt Inc.', 2011, 2010, 1993, 5);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Silver Mock Orange', 'Nelco Laboratories, Inc.', 1996, 2001, 2005, 11);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Orange Lichen', 'Chattem, Inc.', 2002, 2007, 2004, 22);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Small Cordgrass', 'Neat Feat Products Limited', 1993, 1999, 1986, 15);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Kanab Yucca', 'Apotheca Company', 1995, 1999, 1998, 18);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Juniper Polytrichum Moss', 'Nelco Laboratories, Inc.', 2006, 1994, 2005, 4);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Black Oats', 'AMOREPACIFIC', 2009, 1988, 1992, 20);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Arizona Ragwort', 'Praxair Distribution Southest LLC', 1986, 2007, 1997, 22);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Stonewood', 'Wal-Mart Stores Inc', 1992, 1995, 2003, 2);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Spiderwisp', 'JN Pharm', 2011, 1993, 1993, 36);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Green Bristlegrass', 'Aptalis Pharma US, Inc.', 2011, 1995, 2012, 40);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Horehound', 'HEB', 2009, 2009, 2012, 10);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Wedge Sandmat', 'The Mentholatum Company', 2011, 1992, 1990, 2);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Canby''s Aster', 'Cardinal Health', 1993, 2006, 2006, 19);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Riverside Spineflower', 'CVS Pharmacy', 1994, 2006, 2005, 33);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Island Gooseberry', 'Sandoz Inc', 2013, 2013, 2002, 10);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Nieuwland''s Blazing Star', 'Apotheca, Inc.', 1989, 1996, 2012, 11);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Button Fern', 'Proficient Rx LP', 2012, 2007, 1989, 32);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Nevada Oryctes', 'Cardinal Health', 2006, 2010, 2008, 20);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Dunn''s Lobelia', 'St Marys Medical Park Pharmacy', 1994, 1984, 1996, 14);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Lecidea Lichen', 'Save-A-Lot Food Stores Ltd', 1994, 2007, 1987, 14);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Amur Maple', 'sanofi-aventis U.S. LLC', 2001, 2008, 1989, 2);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Rosebud Orchid', 'Antigen Laboratories, Inc.', 2012, 2008, 2008, 9);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Lady''s Tresses', 'REMEDYREPACK INC.', 2009, 1992, 2009, 9);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Dot Lichen', 'NexAir, LLC', 2007, 1992, 2005, 5);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Purpledisk Sunflower', 'Med-Health Pharma, LLC', 1998, 2008, 2011, 36);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Mayten', 'Reckitt Benckiser LLC', 2012, 1969, 1994, 1);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Ryegrass', 'PD-Rx Pharmaceuticals, Inc.', 1997, 2011, 2006, 20);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Clustered Field Sedge', 'NATURE REPUBLIC CO., LTD.', 1998, 1988, 1993, 22);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Spreading Bedstraw', 'ViiV Healthcare Company', 1998, 1989, 1997, 22);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Engelmann''s Sage', 'King Bio Inc.', 2004, 2008, 2002, 17);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Lyall''s Goldenweed', 'Cover FX Skin Care, Inc.', 1987, 1994, 2007, 36);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Incense Cedar', 'Touchless Care Concepts LLC', 2006, 1986, 2010, 34);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Tufted Alpine Saxifrage', 'E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.', 1994, 1997, 2000, 8);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('White Insideout Flower', 'Aphena Pharma Solutions - Tennessee, LLC', 2008, 1994, 1997, 40);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('American Burnweed', 'Cronus Pharma LLC', 2004, 2011, 2006, 16);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Pygmy Clover', 'bryant ranch prepack', 1993, 1981, 2012, 18);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Navel Lichen', 'American Regent, Inc.', 2008, 1985, 2005, 26);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Cottonwood', 'NATURE REPUBLIC CO., LTD.', 2010, 1993, 2011, 30);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Whitetassels', 'State of Florida DOH Central Pharmacy', 2001, 2011, 2002, 7);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Sedge', 'Dr. Fresh, Inc.', 1994, 2004, 2005, 2);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Angelon', 'ALK-Abello, Inc.', 2003, 2008, 2011, 21);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Garcinia', 'Geri-Care Pharmaceuticals, Corp', 1999, 2009, 1992, 20);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Chaenothecopsis Lichen', 'L. Perrigo Company', 2009, 2011, 1986, 36);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Horsehair Lichen', 'MCR American Pharmaceuticals, Inc.', 2002, 1998, 1993, 8);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Ale', 'ALK-Abello, Inc.', 2010, 2002, 1988, 7);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Bunge''s Smartweed', 'Mission Hills S.A de C.V', 2007, 1994, 2009, 9);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Least Willow', 'Zydus Pharmaceuticals (USA) Inc.', 2005, 2007, 2007, 6);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('African Jointfir', 'Actavis Inc.', 2004, 2009, 2011, 24);
insert into wine_wine (winename, producer, year, drinkfrom, drinkto, nmbrbottles) values ('Snailwood', 'Unit Dose Services', 2003, 1989, 2005, 5);
