# Generated by Django 5.0.10 on 2024-12-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0004_wine_warehouse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wine",
            options={"ordering": ["drinkto", "country", "region", "year"]},
        ),
        migrations.AddField(
            model_name="wine",
            name="winetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-", "-"),
                    ("red", "Rot"),
                    ("white", "Weiss"),
                    ("rose", "Rosé"),
                    ("bubbles", "Bubbles"),
                    ("sweet", "Süsswein"),
                    ("spirit", "Spirituosen"),
                ],
                max_length=12,
            ),
        ),
    ]
