# Generated by Django 5.2.1 on 2025-10-17 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winename", models.CharField(max_length=200)),
                ("producer", models.CharField(blank=True, max_length=200)),
                ("grapes", models.CharField(blank=True, max_length=200)),
                (
                    "winetype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("-", "-"),
                            ("red", "Rot"),
                            ("white", "Weiss"),
                            ("rose", "Rosé"),
                            ("bubbles", "Bubbles"),
                            ("sweet", "Süsswein"),
                            ("spirit", "Spirituosen"),
                        ],
                        default="-",
                        max_length=12,
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("-", "-"),
                            ("Australien", "Australien"),
                            ("Frankreich", "Frankreich"),
                            ("Deutschland", "Deutschland"),
                            ("Italien", "Italien"),
                            ("Österreich", "Österreich"),
                            ("Portugal", "Portugal"),
                            ("Schweiz", "Schweiz"),
                            ("Spanien", "Spanien"),
                            ("Südafrika", "Südafrika"),
                            ("USA", "USA"),
                        ],
                        default="-",
                        max_length=12,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=200)),
                ("purchase", models.DateField(blank=True, null=True)),
                ("price", models.CharField(blank=True, default=0, max_length=12)),
                ("dealer", models.CharField(blank=True, max_length=200)),
                ("drinkfrom", models.IntegerField(blank=True, null=True)),
                ("drinkto", models.IntegerField(blank=True, null=True)),
                ("nmbrbottles", models.IntegerField(default=0)),
                ("warehouse", models.CharField(blank=True, max_length=200)),
                ("notes", models.CharField(blank=True, max_length=400)),
                ("editdate", models.DateField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["drinkto", "country", "region", "year"],
            },
        ),
    ]
