# Generated by Django 2.0.4 on 2018-08-30 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('wine', '0001_initial'), ('wine', '0002_auto_20180411_0511'), ('wine', '0003_auto_20180411_0518'), ('wine', '0004_wine_year'), ('wine', '0005_auto_20180422_1804'), ('wine', '0006_auto_20180830_2348')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winename', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=200)),
                ('drinkfrom', models.CharField(default=2018, max_length=200)),
                ('drinkto', models.CharField(default=2018, max_length=200)),
                ('grapes', models.CharField(default=2018, max_length=200)),
                ('nmbrbottles', models.IntegerField(default=0)),
                ('year', models.CharField(default=1970, max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('editdate', models.DateTimeField(null=True)),
                ('entrydate', models.DateTimeField(null=True, verbose_name='date published')),
                ('notes', models.CharField(max_length=400, null=True)),
                ('purchase', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
