# Generated by Django 3.0.2 on 2020-05-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winename', models.CharField(blank=True, max_length=200)),
                ('producer', models.CharField(blank=True, max_length=200)),
                ('grapes', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('purchase', models.DateField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0)),
                ('dealer', models.CharField(blank=True, max_length=200)),
                ('drinkfrom', models.CharField(blank=True, max_length=200)),
                ('drinkto', models.CharField(blank=True, max_length=200)),
                ('nmbrbottles', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=400)),
                ('editdate', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'region', 'year'],
            },
        ),
    ]
