# Generated by Django 3.0.2 on 2020-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
