# Generated by Django 2.0.4 on 2018-04-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='Produzent',
            new_name='producer',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='Weinname',
            new_name='winename',
        ),
    ]
