# Generated by Django 2.0.4 on 2018-04-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20180411_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='drinkfrom',
            field=models.CharField(default=2018, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='drinkto',
            field=models.CharField(default=2018, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='grapes',
            field=models.CharField(default=2018, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='nmbrbottles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
