# Generated by Django 3.2.8 on 2021-10-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_wine_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='storage',
        ),
    ]
