# Generated by Django 3.0.2 on 2020-05-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20200505_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
