# Generated by Django 3.0.3 on 2020-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20200506_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
