# Generated by Django 2.0.4 on 2018-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20180411_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.CharField(default=1970, max_length=200),
            preserve_default=False,
        ),
    ]
