# Generated by Django 3.0.2 on 2020-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20200508_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='drinkfrom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
