# Generated by Django 2.0.4 on 2018-04-22 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wine', '0004_wine_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='wine',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='editdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='entrydate',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='wine',
            name='notes',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='purchase',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
