# Generated by Django 5.1.4 on 2024-12-23 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_wine_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['drinkto', 'country', 'region', 'year']},
        ),
    ]
