# Generated by Django 3.0.2 on 2020-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_auto_20200511_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(choices=[('-', '-'), ('Australien', 'Australien'), ('Frankreich', 'Frankreich'), ('Deutschland', 'Deutschland'), ('Italien', 'Italien'), ('Österreich', 'Österreich'), ('Portugal', 'Portugal'), ('Schweiz', 'Schweiz'), ('Spanien', 'Spanien'), ('Südafrika', 'Südafrika'), ('USA', 'USA')], max_length=12),
        ),
        migrations.AlterField(
            model_name='wine',
            name='drinkto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='wine',
            name='purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
