# Generated by Django 2.0.4 on 2018-08-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_auto_20180422_1804'),
    ]

