# Generated by Django 3.0.3 on 2020-06-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_wine_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='owner',
        ),
    ]
