# Generated by Django 3.0.2 on 2020-06-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('wine', '0005_wine_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
