# Generated by Django 5.1.4 on 2024-12-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0005_alter_wine_options"),
        ("wine", "0007_alter_wine_winetype"),
    ]

    operations = []
