# Generated by Django 5.1.4 on 2025-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0008_merge_20241229_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="winetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-", "-"),
                    ("red", "Rot"),
                    ("white", "Weiss"),
                    ("rose", "Rosé"),
                    ("bubbles", "Bubbles"),
                    ("sweet", "Süsswein"),
                    ("spirit", "Spirituosen"),
                ],
                default="-",
                max_length=12,
            ),
        ),
    ]
