# Generated by Django 3.0.2 on 2020-01-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0008_auto_20180831_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='wine',
            name='purchase',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
