# Generated by Django 3.0.3 on 2020-06-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0006_remove_wine_owner'),
        ('wine', '0009_auto_20200603_2142'),
    ]

    operations = [
    ]
