# Generated by Django 3.0.2 on 2020-01-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0009_auto_20200117_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='drinkfrom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='drinkto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grapes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='nmbrbottles',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='producer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='winename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
