# Generated by Django 3.0.2 on 2020-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0012_auto_20200119_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
