# Generated by Django 3.0.2 on 2020-01-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0013_auto_20200119_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='nmbrbottles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
