# Generated by Django 3.0.2 on 2020-06-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0013_auto_20200606_1546'),
        ('wine', '0011_auto_20200603_2249'),
    ]

    operations = [
    ]
