# Generated by Django 3.0.2 on 2020-01-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0014_auto_20200119_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='nmbrbottles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
