# Generated by Django 3.0.2 on 2020-01-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0016_auto_20200119_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='editdate',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='entrydate',
        ),
    ]
