# Generated by Django 3.0.2 on 2020-01-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0017_auto_20200125_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='editdate',
            field=models.DateField(auto_now=True),
        ),
    ]
