# Generated by Django 3.0.2 on 2020-02-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0018_wine_editdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['country', 'region']},
        ),
        migrations.AlterField(
            model_name='wine',
            name='purchase',
            field=models.DateField(blank=True, max_length=200),
        ),
    ]
