# Generated by Django 3.0.2 on 2020-02-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0019_auto_20200216_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='purchase',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
