# Generated by Django 3.0.3 on 2020-02-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0020_auto_20200224_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['country', 'region', 'year']},
        ),
    ]
