# Generated by Django 3.0.2 on 2020-03-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0022_auto_20200320_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(),
        ),
    ]
