# Generated by Django 3.0.3 on 2020-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0023_auto_20200320_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(max_length=8),
        ),
    ]
