# Generated by Django 3.0.2 on 2020-03-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0025_auto_20200321_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='dealer',
        ),
    ]
