# Generated by Django 3.0.3 on 2020-03-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0027_remove_wine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='foobar',
            field=models.IntegerField(default=0),
        ),
    ]
