# Generated by Django 3.0.3 on 2020-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0030_auto_20200329_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
