# Generated by Django 3.0.3 on 2020-04-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0031_auto_20200329_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
