# Generated by Django 3.0.3 on 2020-04-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0032_auto_20200420_2354'),
        ('wine', '0032_auto_20200420_2119'),
    ]

    operations = [
    ]
